01-basics/02-MarkedList
js-tasks-ru/vue-20210511_nkinash pull request #3
Opened 2021-05-17 21:05 UTC by nkinash

2021-05-17 21:06 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-05-17 21:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-05-17 21:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-05-17 22:10 UTC, ShGKme requested changes
В `02-MarkedList` требуется поменять поиск по emails в шаблоне на подготовку данных в вычисляемом свойстве.

`03-MeetupTitle` - принята.

2021-05-17 22:10 UTC, ShGKme commented on 01-basics/02-MarkedList/script.js
> +  }
Вместо вычисляемого свойства, которое фильтрует список email, а затем метода, который опять выполняет поиск уже в шаблоне, лучше сделать вычисляемое свойство, которое возвращает тот же список `emails`, но дополнив его данными, необходимыми для их маркировки при выводе списка. Это позволит и избавиться от лишней работы, и сделает шаблон чистым, без протекания логики и вызова метода поиска.

2021-05-17 22:10 UTC, ShGKme commented on 01-basics/03-MeetupTitle/index.html
> +    <input type="radio" name="radio" value="5" v-model="checked">5
Можно использовать `v-for="i in 5"`.

2021-05-18 08:51 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-05-18 09:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-05-18 09:16 UTC, ShGKme approved these changes
Все задачи приняты 👍

2021-05-18 09:16 UTC, merged